title: Hong's Blog
theme: jekyll-theme-tactile

# The layout for sidebar and content of site.
layout:
  # The width of the content area in website.
  content: 968px
  # The width of the sidebar in website.
  sidebar: 400px
  # The width between the content and the sidebar.
  content_sidebar_gap: 30px
  # The padding property of the main tag.
  # e.g. Usage:
  # 20px
  # 20px 30px
  # 20px 20px 30px
  # 20px 30px 40px 25px
  main_padding:
    # Take effect when screen width in: [768px, Infinity)
    default: 20px
    # Take effect when screen width in: [576px, 768px)
    tablet: 15px
    # Take effect when screen width in: [0px, 576px)
    mobile: 10px
